apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resource-consumer
  name: resource-consumer
  namespace: default
spec:
  selector:
    matchLabels:
      app: resource-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: resource-consumer
    spec:
      containers:
        - image: gcr.io/k8s-staging-e2e-test-images/resource-consumer:1.9
          name: resource-consumer
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: resource-consumer
  namespace: default
spec:
  selector:
    app: resource-consumer
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
